<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Gerenciador de Gastos Pessoais</title>
	<meta charset="UTF-8">
    <meta name='viewport'content='width=device-width, initial-scale=0.75'>

	<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	
	<link rel="stylesheet" href="/assets/css/estilo.css">
		
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<link href="/assets/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    
	<link rel="icon" href="assets/img/favicon2.ico">
	<script src="/assets/lib/jquery/jquery.min.js"></script>
	<script src="/assets/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Custom styles for this template -->


<!--img/logo.png-->
</head>

<body>
	<header>
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
	<img src="assets/img/finance.png" alt="some text" width=60 height=50>
	  <h2>GESTÃO PESSOAL </h2>	  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
		  <a class="nav-link"  href="<?=HOME;?>/">Home</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="<?=HOME;?>/despesas">Despesas</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="<?=HOME;?>/receitas">Receitas</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="<?=HOME;?>/categorias">Categorias</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="<?=HOME;?>/balanco">Balanço</a>
					</li>
					<li class="nav-item">
					<?php if(\Code\Session\Session::has('user')): ?>
                    <li>
                        <a class="nav-link" href="<?=HOME;?>/auth/logout">Deslogar</a>
                    </li>
                <?php else: ?>
                    <li>
                        <a class="nav-link" href="<?=HOME;?>/auth/login">Login</a>
                    </li>
				<?php endif;?>
					</li>
          </ul>
      </div>
    </div>
  </nav>
</header>


<div id="conteudo" class="container">