<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">
	<div class="col-md-12">
		<h1>Editar Categoria</h1>
		<hr>
	</div>
	<div class="col-md-12">
		<form method="post" action="<?=HOME;?>/categorias/edit/<?=$this->categorias['id'];?>">
			<div class="form-group">
				<label for="exampleInputEmail1">Categoria</label>
				<input type="text" name="nome" class="form-control" id="exampleInputEmail1" placeholder="Nome Categoria"
                value="<?=$this->categorias['nome'];?>">
			</div>			

			<button type="submit" class="btn btn-success btn-lg pull-right">Atualizar Categoria</button>
		</form>
	</div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
