<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

    <div class="jumbotron">
        <h1>Gerenciador de Gastos Pessoais</h1>
        <p>
            Projeto criado para a materia de Programação Orientada a Objeto do Curso de 
            Tecnologia em Analise de Desenvolvimetno.
        </p>
        <p>
            <a class="btn btn-lg btn-success" href="https://assis.ifpr.edu.br/nossos-cursos/cursos-superiores/tads/" role="button">Saiba mais &raquo;</a>
        </p>
    </div>

    <div class="col-md-12">

    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
