<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
	<div class="col-md-12">
		<h1>Balanço do dia</h1>
		<hr>
	</div>
	
	
	<br>
	<div class="col-md-12">
		<table class="table">
			<thead>
			<tr>
				<th>Data</th>
				<th>Receita</th>
				<th>Despesa</th>
				<th>Saldo do dia</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach($this->despesas as $e):?>
			<tr>
				<td><?=date('d/m/Y H:i:s', strtotime($e['updated_at']));?></td>
				<td>R$ <?=number_format($e['total_rec'], 2, ',', '.');?></td>	
				<td>R$ <?=number_format($e['total_desp'], 2, ',', '.');?></td>
				<td>R$ <?=number_format($e['total_rec'] - $e['total_desp'], 2, ',', '.');?></td>				
				
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
