<?php require VIEWS_PATH . 'includes/header.phtml';?>
<script type="text/javascript" src="dist/excellentexport.js"></script>

<div class="container">
	<div class="col-md-12">
		<h1>Balanço do dia</h1>
		<hr>
	</div>
	
	
	<br>
	<a download="saldoDia.xls" href="#" onclick="return ExcellentExport.excel(this, 'datatable', 'Sheet Name Here');" class="btn btn-success">Excel</a>
<a download="SaldoDia.csv" href="#" onclick="return ExcellentExport.csv(this, 'datatable');" class="btn btn-success">CSV</a>
<!-- new API, xlsx -->

	<div class="col-md-12">
		<table class="table" id="datatable">
			<thead>
			<tr>
				<th>Data</th>
				<th>Receita</th>
				<th>Despesa</th>
				<th>Saldo do dia</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach($this->balanco as $e):?>
			<tr>
				<td><?=date('d/m/Y H:i:s', strtotime($e['updated_at']));?></td>
				<td>R$ <?=number_format($e['total_rec'], 2, ',', '.');?></td>	
				<td>R$ <?=number_format($e['total_desp'], 2, ',', '.');?></td>
				<td>R$ <?=number_format($e['total_rec'] - $e['total_desp'], 2, ',', '.');?></td>				
				
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>

</div>
<script src="http://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
<script>
    require(['dist/excellentexport'], function(ee) {
        window.ExcellentExport = ee;
    });
</script>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
